name: ci

on:
  push:
    branches:
      - master
      - main

steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '12.13.0'
- run: yarn install
- run: yarn lint
- run: yarn test
